name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Git
      run: sudo apt-get install git

    - name: Clone repository
      run: git clone https://github.com/LSPosed/MagiskOnWSALocal.git

    - name: Install dependencies
      run: |
        cd MagiskOnWSALocal
        # insert the commands to install dependencies here
        # since dependencies are not specified, I will leave this comment here for you to replace with the appropriate commands

    - name: Install dependencies
      run: |
        cd MagiskOnWSALocal
        # Install qemu-img
        sudo apt-get update
        sudo apt-get install -y qemu-utils
        # insert the commands to install other dependencies here
        # since dependencies are not specified, I will leave this comment here for you to replace with the appropriate commands

    - name: Build
      run: |
        cd MagiskOnWSALocal
        chmod +x ./scripts/build.sh
        ./scripts/build.sh --arch x64 --release-type retail --root-sol magisk --gapps-brand MindTheGapps --remove-amazon --compress --magisk-ver stable --compress-format 7z

    - name: Setup GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh

    - name: Authenticate with GitHub CLI
      run: echo "${{ secrets.PUBLISH_TOKEN }}" | gh auth login --with-token

    - name: Publish new release
      run: |
        cd MagiskOnWSALocal/output
        FILE=$(ls *.7z)
        VERSION=$(date +%Y%m%d%H%M)
        gh release create "Build-$VERSION" $FILE -R yige-yigeren/MagiskOnWSAAuto -t "Build $(date +%Y%m%d)" -n "Automatic build" --prerelease
        gh release delete "Build-$(date --date='-1 day' +%Y%m%d)" -y -R yige-yigeren/MagiskOnWSAAuto